# Generated by Django 4.1 on 2022-08-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sluf',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
