# Generated by Django 4.1 on 2022-08-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sluf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sluf',
            new_name='slug',
        ),
    ]
