# Generated by Django 4.1 on 2022-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('serialNum', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=13)),
                ('content', models.TextField()),
            ],
        ),
    ]
